### PR TITLE
Added TERM signal handler

### PR DESCRIPTION
**Pull request by furgin**
Added a signal handler for SIGTERM

I'm not sure if needs the special handling for the second signal of this type.

### CODE REVIEW

**Comment by furgin** [comment]
fixes #356

**Comment by Hornwitser** [comment]
Pretty sure you'll run into the same problem with the slave process.

**Comment by furgin** [comment]
Good call, ill make the change and test it out locally then update the PR

**Review by Danielv123 — APPROVED** [review]
Makes sense.

**Review by psihius — APPROVED** [review]

**Pull request merged**
